language: cpp

os:
  - linux

dist: xenial

compiler:
  - gcc
  - clang

notifications:
  email: false

sudo: false

cache:
  - apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libboost1.58-all-dev

matrix:
  allow_failures:
    - compiler: clang
    - os: osx

script:
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_ENV_VAR=CC -DCMAKE_CXX_COMPILER_ENV_VAR=CXX
  - make -j4
  - ctest -V
