language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

notifications:
  email: false

sudo: false

cache:
  - apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - g++-4.9
    - clang-3.6
    - libboost1.55-all-dev

matrix:
  allow_failures:
    - compiler: clang
    - os: osx

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_ENV_VAR=CC -DCMAKE_CXX_COMPILER_ENV_VAR=CXX
  - make -j4
  - ctest -V
